### ISSUE TITLE
the experimental syntax 'jsx' isn't currently enabled

### ISSUE THREAD

**Issue by fjxhkj** [violentmonkey/generator-userscript#4]
On Windows 10, after run the install cmd, and run `yarn build` or `yarn dev`, I got this errors:

```bash
@ D:\links\dev\chrome_greasemonkey\vm_test
# yarn build
yarn run v1.22.10
$ run-s ci clean
$ run-s lint
$ eslint --ext .js .
$ del-cli dist
$ cross-env NODE_ENV=production run-s build:js
$ rollup -c rollup.conf.js

src/index.js → dist/index.user.js...
(!) Plugin replace: @rollup/plugin-replace: 'preventAssignment' currently defaults to false. It is recommended to set this option to `true`, as the next major version will default this option to `true`.
[!] (plugin babel) SyntaxError: D:\dev\chrome_greasemonkey\vm_test\src\app.js: Support for the experimental syntax 'jsx' isn't currently enabled (8:5):

   6 | export function getGreetings() {
   7 |   return (
>  8 |     <>
     |     ^
   9 |       <div className={styles.panel}>
  10 |         hello
  11 |       </div>

Add @babel/preset-react (https://git.io/JfeDR) to the 'presets' section of your Babel config to enable transformation.
If you want to leave it as-is, add @babel/plugin-syntax-jsx (https://git.io/vb4yA) to the 'plugins' section to enable parsing.
..\..\..\..\dev\chrome_greasemonkey\vm_test\src\app.js (8:4)
SyntaxError: D:\dev\chrome_greasemonkey\vm_test\src\app.js: Support for the experimental syntax 'jsx' isn't currently enabled (8:5):

   6 | export function getGreetings() {
   7 |   return (
>  8 |     <>
     |     ^
   9 |       <div className={styles.panel}>
  10 |         hello
  11 |       </div>

Add @babel/preset-react (https://git.io/JfeDR) to the 'presets' section of your Babel config to enable transformation.
If you want to leave it as-is, add @babel/plugin-syntax-jsx (https://git.io/vb4yA) to the 'plugins' section to enable parsing.
    at Parser._raise (D:\dev\chrome_greasemonkey\vm_test\node_modules\@babel\parser\src\parser\error.js:134:45)
    at Parser.raiseWithData (D:\dev\chrome_greasemonkey\vm_test\node_modules\@babel\parser\src\parser\error.js:129:17)
    at Parser.expectOnePlugin (D:\dev\chrome_greasemonkey\vm_test\node_modules\@babel\parser\src\parser\util.js:191:18)
    at Parser.parseExprAtom (D:\dev\chrome_greasemonkey\vm_test\node_modules\@babel\parser\src\parser\expression.js:1217:18)
    at Parser.parseExprSubscripts (D:\dev\chrome_greasemonkey\vm_test\node_modules\@babel\parser\src\parser\expression.js:615:23)
    at Parser.parseUpdate (D:\dev\chrome_greasemonkey\vm_test\node_modules\@babel\parser\src\parser\expression.js:595:21)
    at Parser.parseMaybeUnary (D:\dev\chrome_greasemonkey\vm_test\node_modules\@babel\parser\src\parser\expression.js:562:23)
    at Parser.parseExprOps (D:\dev\chrome_greasemonkey\vm_test\node_modules\@babel\parser\src\parser\expression.js:366:23)
    at Parser.parseMaybeConditional (D:\dev\chrome_greasemonkey\vm_test\node_modules\@babel\parser\src\parser\expression.js:331:23)
    at Parser.parseMaybeAssign (D:\dev\chrome_greasemonkey\vm_test\node_modules\@babel\parser\src\parser\expression.js:286:21)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "build:js" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

then I try to add `@babel/preset-react` and `@babel/plugin-syntax-jsx` into the `.babelrc.js` on the right places, but not working ...

How to fix this ?

**Comment by gera2ld** [comment]
Do you still get this error after a fresh install without any change?
I just tested it on macOS and it worked as expected. I don't have a Windows system at hand and will look into this later.

**Comment by fjxhkj** [comment]
I did run a fresh installation yesterday and only submitted the issue after trying many times to resolve the problem.Did not expect to change a computer is no problem...
I tried to perform the same process on another computer without any errors.I suspect it is a problem with the environment configuration of the previous computer, which is being investigated.
It should not be the problem of this project. Sorry to bother you...

**Comment by gera2ld** [comment]
The path `..\..\..\..\dev\chrome_greasemonkey\vm_test\src\app.js (8:4)` looks strange, maybe there is an unexpected babel config file at `D:\dev`?
