### ISSUE TITLE
Can neither run dev server nor build

### ISSUE THREAD

**Issue by KnifeFed** [violentmonkey/generator-userscript#7]
On a freshly created project I get this:

<details>
<summary>log</summary>

```
$ npx -p https://github.com/violentmonkey/generator-userscript.git -p yo yo @violentmonkey/userscript                                                                                                                  
? Your project name test1234
? Do you want to use TypeScript? Yes
   create package.json
   create LICENSE
   create README.md
   create .babelrc.js
   create .browserslistrc
   create .editorconfig
   create .eslintignore
   create .gitignore
   create rollup.conf.js
   create scripts/util.js
   create .eslintrc.js
   create tsconfig.json
   create tslint.json
   create src/meta.js
   create src/index.ts
   create src/app.tsx
   create src/index.d.ts
   create src/style.module.css
1.22.19
yarn add v1.22.19
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning rollup-plugin-babel@4.4.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-babel.
warning @gera2ld/plaid > babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
warning @gera2ld/plaid > svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
warning @gera2ld/plaid > precss@4.0.0: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning @gera2ld/plaid > svgo > stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
warning @gera2ld/plaid > precss > postcss-preset-env > postcss-color-functional-notation > postcss-values-parser > flatten@1.0.3: flatten is deprecated in favor of utility frameworks such as lodash.
warning cssnano > cssnano-preset-default > postcss-svgo > svgo > stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "@gera2ld/plaid > eslint-config-airbnb@18.2.1" has unmet peer dependency "eslint-plugin-react-hooks@^4 || ^3 || ^2.3.0 || ^1.7.0".
warning " > @gera2ld/plaid-react@1.5.5" has unmet peer dependency "@gera2ld/plaid-webpack@*".
warning "@gera2ld/plaid-react > @babel/preset-react@7.18.6" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@gera2ld/plaid-react > @babel/preset-react > @babel/plugin-transform-react-display-name@7.18.6" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@gera2ld/plaid-react > @babel/preset-react > @babel/plugin-transform-react-jsx-development@7.18.6" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@gera2ld/plaid-react > @babel/preset-react > @babel/plugin-transform-react-jsx@7.18.10" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@gera2ld/plaid-react > @babel/preset-react > @babel/plugin-transform-react-pure-annotations@7.18.6" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@gera2ld/plaid-react > @babel/preset-react > @babel/plugin-transform-react-jsx > @babel/plugin-syntax-jsx@7.18.6" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-typescript > @babel/plugin-transform-typescript@7.18.12" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-typescript > @babel/plugin-transform-typescript > @babel/plugin-syntax-typescript@7.18.6" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@typescript-eslint/eslint-plugin > @typescript-eslint/type-utils@5.33.1" has unmet peer dependency "eslint@*".
warning "@typescript-eslint/eslint-plugin > @typescript-eslint/utils@5.33.1" has unmet peer dependency "eslint@^6.0.0 || ^7.0.0 || ^8.0.0".
warning "@typescript-eslint/eslint-plugin > @typescript-eslint/utils > eslint-utils@3.0.0" has unmet peer dependency "eslint@>=5".
warning " > rollup-plugin-babel@4.4.0" has unmet peer dependency "@babel/core@7 || ^7.0.0-rc.2".
warning " > @babel/preset-typescript@7.18.6" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > @typescript-eslint/parser@5.33.1" has unmet peer dependency "eslint@^6.0.0 || ^7.0.0 || ^8.0.0".
warning " > @typescript-eslint/eslint-plugin@5.33.1" has unmet peer dependency "eslint@^6.0.0 || ^7.0.0 || ^8.0.0".
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
success Saved 485 new dependencies.
info Direct dependencies
├─ @babel/preset-typescript@7.18.6
├─ @gera2ld/plaid-react@1.5.5
├─ @gera2ld/plaid@1.5.6
├─ @rollup/plugin-alias@3.1.9
├─ @rollup/plugin-commonjs@22.0.2
├─ @rollup/plugin-node-resolve@13.3.0
├─ @rollup/plugin-replace@4.0.0
├─ @typescript-eslint/eslint-plugin@5.33.1
├─ @typescript-eslint/parser@5.33.1
├─ cross-env@7.0.3
├─ cssnano@5.1.13
├─ del-cli@5.0.0
├─ husky@8.0.1
├─ postcss-modules@5.0.0
├─ postcss@8.4.16
├─ rollup-plugin-babel@4.4.0
├─ rollup@2.78.1
└─ typescript@4.7.4
info All dependencies
├─ @ampproject/remapping@2.2.0
├─ @babel/core@7.18.10
├─ @babel/helper-builder-binary-assignment-operator-visitor@7.18.9
├─ @babel/helper-compilation-targets@7.18.9
├─ @babel/helper-explode-assignable-expression@7.18.6
├─ @babel/helper-remap-async-to-generator@7.18.9
├─ @babel/helper-replace-supers@7.18.9
├─ @babel/helper-string-parser@7.18.10
├─ @babel/helper-wrap-function@7.18.11
├─ @babel/helpers@7.18.9
├─ @babel/highlight@7.18.6
├─ @babel/parser@7.18.11
├─ @babel/plugin-bugfix-safari-id-destructuring-collision-in-function-expression@7.18.6
├─ @babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining@7.18.9
├─ @babel/plugin-proposal-async-generator-functions@7.18.10
├─ @babel/plugin-proposal-class-properties@7.18.6
├─ @babel/plugin-proposal-class-static-block@7.18.6
├─ @babel/plugin-proposal-decorators@7.18.10
├─ @babel/plugin-proposal-dynamic-import@7.18.6
├─ @babel/plugin-proposal-export-default-from@7.18.10
├─ @babel/plugin-proposal-export-namespace-from@7.18.9
├─ @babel/plugin-proposal-function-sent@7.18.6
├─ @babel/plugin-proposal-json-strings@7.18.6
├─ @babel/plugin-proposal-logical-assignment-operators@7.18.9
├─ @babel/plugin-proposal-nullish-coalescing-operator@7.18.6
├─ @babel/plugin-proposal-numeric-separator@7.18.6
├─ @babel/plugin-proposal-object-rest-spread@7.18.9
├─ @babel/plugin-proposal-optional-catch-binding@7.18.6
├─ @babel/plugin-proposal-pipeline-operator@7.18.9
├─ @babel/plugin-proposal-private-methods@7.18.6
├─ @babel/plugin-proposal-private-property-in-object@7.18.6
├─ @babel/plugin-proposal-throw-expressions@7.18.6
├─ @babel/plugin-proposal-unicode-property-regex@7.18.6
├─ @babel/plugin-syntax-class-properties@7.12.13
├─ @babel/plugin-syntax-decorators@7.18.6
├─ @babel/plugin-syntax-export-default-from@7.18.6
├─ @babel/plugin-syntax-function-sent@7.18.6
├─ @babel/plugin-syntax-import-assertions@7.18.6
├─ @babel/plugin-syntax-import-meta@7.10.4
├─ @babel/plugin-syntax-jsx@7.18.6
├─ @babel/plugin-syntax-pipeline-operator@7.18.6
├─ @babel/plugin-syntax-throw-expressions@7.18.6
├─ @babel/plugin-syntax-top-level-await@7.14.5
├─ @babel/plugin-syntax-typescript@7.18.6
├─ @babel/plugin-transform-arrow-functions@7.18.6
├─ @babel/plugin-transform-async-to-generator@7.18.6
├─ @babel/plugin-transform-block-scoped-functions@7.18.6
├─ @babel/plugin-transform-block-scoping@7.18.9
├─ @babel/plugin-transform-classes@7.18.9
├─ @babel/plugin-transform-computed-properties@7.18.9
├─ @babel/plugin-transform-destructuring@7.18.9
├─ @babel/plugin-transform-dotall-regex@7.18.6
├─ @babel/plugin-transform-duplicate-keys@7.18.9
├─ @babel/plugin-transform-exponentiation-operator@7.18.6
├─ @babel/plugin-transform-for-of@7.18.8
├─ @babel/plugin-transform-function-name@7.18.9
├─ @babel/plugin-transform-literals@7.18.9
├─ @babel/plugin-transform-member-expression-literals@7.18.6
├─ @babel/plugin-transform-modules-amd@7.18.6
├─ @babel/plugin-transform-modules-commonjs@7.18.6
├─ @babel/plugin-transform-modules-systemjs@7.18.9
├─ @babel/plugin-transform-modules-umd@7.18.6
├─ @babel/plugin-transform-named-capturing-groups-regex@7.18.6
├─ @babel/plugin-transform-new-target@7.18.6
├─ @babel/plugin-transform-object-super@7.18.6
├─ @babel/plugin-transform-property-literals@7.18.6
├─ @babel/plugin-transform-react-display-name@7.18.6
├─ @babel/plugin-transform-react-jsx-development@7.18.6
├─ @babel/plugin-transform-react-pure-annotations@7.18.6
├─ @babel/plugin-transform-regenerator@7.18.6
├─ @babel/plugin-transform-reserved-words@7.18.6
├─ @babel/plugin-transform-runtime@7.18.10
├─ @babel/plugin-transform-shorthand-properties@7.18.6
├─ @babel/plugin-transform-spread@7.18.9
├─ @babel/plugin-transform-sticky-regex@7.18.6
├─ @babel/plugin-transform-template-literals@7.18.9
├─ @babel/plugin-transform-typeof-symbol@7.18.9
├─ @babel/plugin-transform-typescript@7.18.12
├─ @babel/plugin-transform-unicode-escapes@7.18.10
├─ @babel/plugin-transform-unicode-regex@7.18.6
├─ @babel/preset-env@7.18.10
├─ @babel/preset-modules@0.1.5
├─ @babel/preset-react@7.18.6
├─ @babel/preset-typescript@7.18.6
├─ @babel/runtime-corejs3@7.18.9
├─ @babel/runtime@7.18.9
├─ @csstools/sass-import-resolve@1.0.0
├─ @gera2ld/plaid-react@1.5.5
├─ @gera2ld/plaid@1.5.6
├─ @jridgewell/gen-mapping@0.1.1
├─ @jridgewell/resolve-uri@3.1.0
├─ @jridgewell/set-array@1.1.2
├─ @nodelib/fs.scandir@2.1.5
├─ @nodelib/fs.stat@2.0.5
├─ @nodelib/fs.walk@1.2.8
├─ @rollup/plugin-alias@3.1.9
├─ @rollup/plugin-commonjs@22.0.2
├─ @rollup/plugin-node-resolve@13.3.0
├─ @rollup/plugin-replace@4.0.0
├─ @trysound/sax@0.2.0
├─ @types/estree@1.0.0
├─ @types/json-schema@7.0.11
├─ @types/json5@0.0.29
├─ @types/minimist@1.2.2
├─ @types/node@18.7.8
├─ @types/normalize-package-data@2.4.1
├─ @types/parse-json@4.0.0
├─ @types/q@1.5.5
├─ @types/resolve@1.17.1
├─ @typescript-eslint/eslint-plugin@5.33.1
├─ @typescript-eslint/parser@5.33.1
├─ @typescript-eslint/type-utils@5.33.1
├─ acorn-jsx@5.3.2
├─ acorn@7.4.1
├─ aggregate-error@4.0.1
├─ ajv@6.12.6
├─ ansi-escapes@4.3.2
├─ ansi-styles@3.2.1
├─ argparse@1.0.10
├─ aria-query@4.2.2
├─ array-union@2.1.0
├─ array.prototype.flat@1.3.0
├─ array.prototype.flatmap@1.3.0
├─ array.prototype.reduce@1.0.4
├─ arrify@1.0.1
├─ ast-types-flow@0.0.7
├─ astral-regex@1.0.0
├─ autoprefixer@9.8.8
├─ axe-core@4.4.3
├─ axobject-query@2.2.0
├─ babel-eslint@10.1.0
├─ babel-plugin-macros@2.8.0
├─ babel-plugin-module-resolver@4.1.0
├─ brace-expansion@1.1.11
├─ braces@3.0.2
├─ builtin-modules@3.3.0
├─ callsites@3.1.0
├─ camelcase-keys@7.0.2
├─ camelcase@6.3.0
├─ caniuse-lite@1.0.30001380
├─ chalk@2.4.2
├─ chardet@0.7.0
├─ clean-stack@4.2.0
├─ cli-cursor@3.1.0
├─ cli-width@3.0.0
├─ clone@1.0.4
├─ coa@2.0.2
├─ color-convert@1.9.3
├─ color-name@1.1.4
├─ color-string@0.3.0
├─ color@0.11.4
├─ commander@4.1.1
├─ commondir@1.0.1
├─ concat-map@0.0.1
├─ confusing-browser-globals@1.0.11
├─ convert-source-map@1.8.0
├─ core-js-compat@3.24.1
├─ core-js-pure@3.24.1
├─ cross-env@7.0.3
├─ cross-spawn@7.0.3
├─ css-blank-pseudo@0.1.4
├─ css-color-function@1.3.3
├─ css-declaration-sorter@6.3.0
├─ css-has-pseudo@0.10.0
├─ css-prefers-color-scheme@3.1.1
├─ css-select-base-adapter@0.1.1
├─ css-select@2.1.0
├─ css-tree@1.1.3
├─ css-what@3.4.2
├─ cssdb@4.4.0
├─ cssesc@3.0.0
├─ cssnano-preset-default@5.2.12
├─ cssnano@5.1.13
├─ csso@4.2.0
├─ damerau-levenshtein@1.0.8
├─ decamelize-keys@1.1.0
├─ decamelize@5.0.1
├─ deep-is@0.1.4
├─ deepmerge@4.2.2
├─ del-cli@5.0.0
├─ del@7.0.0
├─ dom-serializer@0.2.2
├─ domutils@1.7.0
├─ electron-to-chromium@1.4.225
├─ emoji-regex@9.2.2
├─ error-ex@1.3.2
├─ es-array-method-boxes-properly@1.0.0
├─ es-to-primitive@1.2.1
├─ escalade@3.1.1
├─ eslint-config-airbnb-base@14.2.1
├─ eslint-import-resolver-babel-module@5.3.1
├─ eslint-import-resolver-node@0.3.6
├─ eslint-module-utils@2.7.4
├─ eslint-plugin-babel@5.3.1
├─ eslint-plugin-import@2.26.0
├─ eslint-plugin-jsx-a11y@6.6.1
├─ eslint-plugin-react@7.30.1
├─ eslint-rule-composer@0.3.0
├─ eslint-scope@5.1.1
├─ eslint-utils@1.4.3
├─ eslint@6.8.0
├─ espree@6.2.1
├─ esprima@4.0.1
├─ esquery@1.4.0
├─ esrecurse@4.3.0
├─ estraverse@5.3.0
├─ estree-walker@2.0.2
├─ external-editor@3.1.0
├─ fast-deep-equal@3.1.3
├─ fast-glob@3.2.11
├─ fast-json-stable-stringify@2.1.0
├─ fast-levenshtein@2.0.6
├─ fastq@1.13.0
├─ figures@3.2.0
├─ file-entry-cache@5.0.1
├─ fill-range@7.0.1
├─ find-babel-config@1.2.0
├─ find-up@3.0.0
├─ flat-cache@2.0.1
├─ flatted@2.0.2
├─ flatten@1.0.3
├─ fs-extra@8.1.0
├─ fs.realpath@1.0.0
├─ fsevents@2.3.2
├─ function.prototype.name@1.1.5
├─ generic-names@4.0.0
├─ gensync@1.0.0-beta.2
├─ get-symbol-description@1.0.0
├─ glob-parent@5.1.2
├─ globby@11.1.0
├─ graceful-fs@4.2.10
├─ hard-rejection@2.1.0
├─ has-ansi@2.0.0
├─ has-bigints@1.0.2
├─ has-flag@3.0.0
├─ hosted-git-info@4.1.0
├─ husky@8.0.1
├─ iconv-lite@0.4.24
├─ icss-replace-symbols@1.1.0
├─ import-fresh@3.3.0
├─ imurmurhash@0.1.4
├─ inflight@1.0.6
├─ inherits@2.0.4
├─ inquirer@7.3.3
├─ is-arrayish@0.2.1
├─ is-bigint@1.0.4
├─ is-boolean-object@1.1.2
├─ is-builtin-module@3.2.0
├─ is-callable@1.2.4
├─ is-core-module@2.10.0
├─ is-date-object@1.0.5
├─ is-extglob@2.1.1
├─ is-module@1.0.0
├─ is-negative-zero@2.0.2
├─ is-number-object@1.0.7
├─ is-number@7.0.0
├─ is-path-cwd@3.0.0
├─ is-path-inside@4.0.0
├─ is-plain-obj@1.1.0
├─ is-reference@1.2.1
├─ is-regex@1.1.4
├─ is-shared-array-buffer@1.0.2
├─ is-string@1.0.7
├─ is-symbol@1.0.4
├─ is-weakref@1.0.2
├─ js-base64@2.6.4
├─ js-tokens@4.0.0
├─ jsesc@2.5.2
├─ json-parse-even-better-errors@2.3.1
├─ json-schema-traverse@0.4.1
├─ json-stable-stringify-without-jsonify@1.0.1
├─ json5@2.2.1
├─ jsonfile@4.0.0
├─ jsx-ast-utils@3.3.3
├─ kind-of@6.0.3
├─ language-subtag-registry@0.3.22
├─ language-tags@1.0.5
├─ levn@0.3.0
├─ lilconfig@2.0.6
├─ lines-and-columns@1.2.4
├─ loader-utils@3.2.0
├─ locate-path@3.0.0
├─ lodash.camelcase@4.3.0
├─ lodash.debounce@4.0.8
├─ lodash.memoize@4.1.2
├─ lodash.uniq@4.5.0
├─ loose-envify@1.4.0
├─ map-obj@1.0.1
├─ mdn-data@2.0.14
├─ meow@10.1.3
├─ micromatch@4.0.5
├─ mimic-fn@2.1.0
├─ min-indent@1.0.1
├─ minimatch@3.1.2
├─ minimist-options@4.1.0
├─ ms@2.1.2
├─ mute-stream@0.0.8
├─ nanoid@3.3.4
├─ natural-compare@1.4.0
├─ nice-try@1.0.5
├─ node-releases@2.0.6
├─ normalize-range@0.1.2
├─ normalize-url@6.1.0
├─ nth-check@1.0.2
├─ num2fraction@1.2.2
├─ object-assign@4.1.1
├─ object-inspect@1.12.2
├─ object.fromentries@2.0.5
├─ object.getownpropertydescriptors@2.1.4
├─ object.hasown@1.1.1
├─ object.values@1.1.5
├─ onetime@5.1.2
├─ optionator@0.8.3
├─ os-tmpdir@1.0.2
├─ p-limit@2.3.0
├─ p-locate@3.0.0
├─ p-map@5.5.0
├─ p-try@2.2.0
├─ parent-module@1.0.1
├─ parse-json@5.2.0
├─ path-is-absolute@1.0.1
├─ path-key@3.1.1
├─ picomatch@2.3.1
├─ pify@2.3.0
├─ postcss-advanced-variables@3.0.1
├─ postcss-atroot@0.1.3
├─ postcss-attribute-case-insensitive@4.0.2
├─ postcss-calc@7.0.5
├─ postcss-color-function@4.1.0
├─ postcss-color-functional-notation@2.0.1
├─ postcss-color-gray@5.0.0
├─ postcss-color-hex-alpha@5.0.3
├─ postcss-color-mod-function@3.0.3
├─ postcss-color-rebeccapurple@4.0.1
├─ postcss-colormin@5.3.0
├─ postcss-convert-values@5.1.2
├─ postcss-custom-media@7.0.8
├─ postcss-custom-properties@8.0.11
├─ postcss-custom-selectors@5.1.2
├─ postcss-dir-pseudo-class@5.0.0
├─ postcss-discard-comments@5.1.2
├─ postcss-discard-duplicates@5.1.0
├─ postcss-discard-empty@5.1.1
├─ postcss-discard-overridden@5.1.0
├─ postcss-double-position-gradients@1.0.0
├─ postcss-env-function@2.0.2
├─ postcss-extend-rule@2.0.0
├─ postcss-focus-visible@4.0.0
├─ postcss-focus-within@3.0.0
├─ postcss-font-variant@4.0.1
├─ postcss-gap-properties@2.0.0
├─ postcss-image-set-function@3.0.1
├─ postcss-import@12.0.1
├─ postcss-initial@3.0.4
├─ postcss-lab-function@2.0.1
├─ postcss-logical@3.0.0
├─ postcss-media-minmax@4.0.0
├─ postcss-merge-longhand@5.1.6
├─ postcss-merge-rules@5.1.2
├─ postcss-message-helpers@2.0.0
├─ postcss-minify-font-values@5.1.0
├─ postcss-minify-gradients@5.1.1
├─ postcss-minify-params@5.1.3
├─ postcss-minify-selectors@5.2.1
├─ postcss-modules-extract-imports@3.0.0
├─ postcss-modules-local-by-default@4.0.0
├─ postcss-modules-scope@3.0.0
├─ postcss-modules-values@4.0.0
├─ postcss-modules@5.0.0
├─ postcss-nested@4.2.3
├─ postcss-nesting@5.0.0
├─ postcss-normalize-charset@5.1.0
├─ postcss-normalize-display-values@5.1.0
├─ postcss-normalize-positions@5.1.1
├─ postcss-normalize-repeat-style@5.1.1
├─ postcss-normalize-string@5.1.0
├─ postcss-normalize-timing-functions@5.1.0
├─ postcss-normalize-unicode@5.1.0
├─ postcss-normalize-url@5.1.0
├─ postcss-normalize-whitespace@5.1.1
├─ postcss-ordered-values@5.1.3
├─ postcss-overflow-shorthand@2.0.0
├─ postcss-page-break@2.0.0
├─ postcss-place@4.0.1
├─ postcss-plugin-px2rem@0.8.1
├─ postcss-preset-env@6.7.1
├─ postcss-property-lookup@2.0.0
├─ postcss-pseudo-class-any-link@6.0.0
├─ postcss-reduce-initial@5.1.0
├─ postcss-reduce-transforms@5.1.0
├─ postcss-replace-overflow-wrap@3.0.0
├─ postcss-scss@2.1.1
├─ postcss-selector-matches@4.0.0
├─ postcss-selector-not@4.0.1
├─ postcss-svgo@5.1.0
├─ postcss-unique-selectors@5.1.1
├─ postcss@8.4.16
├─ precss@4.0.0
├─ progress@2.0.3
├─ prop-types@15.8.1
├─ punycode@2.1.1
├─ q@1.5.1
├─ queue-microtask@1.2.3
├─ quick-lru@5.1.1
├─ react-is@16.13.1
├─ read-cache@1.0.0
├─ read-pkg-up@8.0.0
├─ read-pkg@6.0.0
├─ redent@4.0.0
├─ regenerate-unicode-properties@10.0.1
├─ regenerator-transform@0.15.0
├─ regexp.prototype.flags@1.4.3
├─ regexpp@3.2.0
├─ regexpu-core@5.1.0
├─ regjsgen@0.6.0
├─ regjsparser@0.8.4
├─ reselect@4.1.6
├─ resolve-from@4.0.0
├─ resolve@1.22.1
├─ restore-cursor@3.1.0
├─ reusify@1.0.4
├─ rgb@0.1.0
├─ rimraf@3.0.2
├─ rollup-plugin-babel@4.4.0
├─ rollup-pluginutils@2.8.2
├─ rollup@2.78.1
├─ run-async@2.4.1
├─ run-parallel@1.2.0
├─ rxjs@6.6.7
├─ safe-buffer@5.1.2
├─ safer-buffer@2.1.2
├─ sax@1.2.4
├─ shebang-command@2.0.0
├─ shebang-regex@3.0.0
├─ signal-exit@3.0.7
├─ slice-ansi@2.1.0
├─ source-map-js@1.0.2
├─ sourcemap-codec@1.4.8
├─ spdx-correct@3.1.1
├─ spdx-exceptions@2.3.0
├─ sprintf-js@1.0.3
├─ string-hash@1.1.3
├─ string-width@3.1.0
├─ string.prototype.matchall@4.0.7
├─ string.prototype.trimend@1.0.5
├─ string.prototype.trimstart@1.0.5
├─ strip-ansi@5.2.0
├─ strip-bom@3.0.0
├─ strip-indent@4.0.0
├─ strip-json-comments@3.1.1
├─ stylehacks@5.1.0
├─ supports-color@5.5.0
├─ svgo@1.3.2
├─ table@5.4.6
├─ tcomb@3.2.29
├─ text-table@0.2.0
├─ through@2.3.8
├─ tmp@0.0.33
├─ to-fast-properties@2.0.0
├─ to-regex-range@5.0.1
├─ trim-newlines@4.0.2
├─ tsconfig-paths@3.14.1
├─ tslib@1.14.1
├─ typescript@4.7.4
├─ unbox-primitive@1.0.2
├─ unicode-canonical-property-names-ecmascript@2.0.0
├─ unicode-match-property-ecmascript@2.0.0
├─ unicode-match-property-value-ecmascript@2.0.0
├─ unicode-property-aliases-ecmascript@2.0.0
├─ universalify@0.1.2
├─ unquote@1.1.1
├─ update-browserslist-db@1.0.5
├─ uri-js@4.4.1
├─ util-deprecate@1.0.2
├─ util.promisify@1.0.1
├─ v8-compile-cache@2.3.0
├─ validate-npm-package-license@3.0.4
├─ which-boxed-primitive@1.0.2
├─ which@2.0.2
├─ word-wrap@1.2.3
├─ write@1.0.3
├─ yallist@4.0.0
├─ yaml@1.10.2
├─ yargs-parser@20.2.9
└─ yocto-queue@0.1.0
✨  Done in 24.10s.
yarn add v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
warning Pattern ["@babel/runtime@^7.18.9"] is trying to unpack in the same destination "/Users/<username>/Library/Caches/Yarn/v6/npm-@babel-runtime-7.18.9-b4fcfce55db3d2e5e080d2490f608a3b9f407f4a-integrity/node_modules/@babel/runtime" as pattern ["@babel/runtime@^7.7.2","@babel/runtime@^7.18.9","@babel/runtime@^7.10.2","@babel/runtime@^7.8.4"]. This could result in non-deterministic behavior, skipping.
[3/4] 🔗  Linking dependencies...
warning " > @babel/preset-typescript@7.18.6" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-typescript > @babel/plugin-transform-typescript@7.18.12" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-typescript > @babel/plugin-transform-typescript > @babel/helper-create-class-features-plugin@7.18.9" has unmet peer dependency "@babel/core@^7.0.0".
warning "@babel/preset-typescript > @babel/plugin-transform-typescript > @babel/plugin-syntax-typescript@7.18.6" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@gera2ld/plaid > eslint-config-airbnb@18.2.1" has unmet peer dependency "eslint-plugin-react-hooks@^4 || ^3 || ^2.3.0 || ^1.7.0".
warning " > @gera2ld/plaid-react@1.5.5" has unmet peer dependency "@gera2ld/plaid-webpack@*".
warning "@gera2ld/plaid-react > @babel/preset-react@7.18.6" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@gera2ld/plaid-react > @babel/preset-react > @babel/plugin-transform-react-display-name@7.18.6" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@gera2ld/plaid-react > @babel/preset-react > @babel/plugin-transform-react-jsx@7.18.10" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@gera2ld/plaid-react > @babel/preset-react > @babel/plugin-transform-react-jsx-development@7.18.6" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@gera2ld/plaid-react > @babel/preset-react > @babel/plugin-transform-react-pure-annotations@7.18.6" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@gera2ld/plaid-react > @babel/preset-react > @babel/plugin-transform-react-jsx > @babel/plugin-syntax-jsx@7.18.6" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > @typescript-eslint/eslint-plugin@5.33.1" has unmet peer dependency "eslint@^6.0.0 || ^7.0.0 || ^8.0.0".
warning "@typescript-eslint/eslint-plugin > @typescript-eslint/type-utils@5.33.1" has unmet peer dependency "eslint@*".
warning "@typescript-eslint/eslint-plugin > @typescript-eslint/utils@5.33.1" has unmet peer dependency "eslint@^6.0.0 || ^7.0.0 || ^8.0.0".
warning "@typescript-eslint/eslint-plugin > @typescript-eslint/utils > eslint-utils@3.0.0" has unmet peer dependency "eslint@>=5".
warning " > @typescript-eslint/parser@5.33.1" has unmet peer dependency "eslint@^6.0.0 || ^7.0.0 || ^8.0.0".
warning " > rollup-plugin-babel@4.4.0" has unmet peer dependency "@babel/core@7 || ^7.0.0-rc.2".
[4/4] 🔨  Building fresh packages...
success Saved 0 new dependencies.
✨  Done in 1.10s.

$ npm run dev                                                                                                                                                                                              

> test1234@0.0.0 dev
> rollup -wc rollup.conf.js

[!] TypeError: resolve is not a function
TypeError: resolve is not a function
    at Object.resolve (/path/to/test1234/scripts/util.js:34:18)
    at getRollupPlugins (/path/to/test1234/scripts/util.js:110:21)
    at Object.<anonymous> (/path/to/test1234/rollup.conf.js:21:16)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at require.extensions.<computed> [as .js] (/path/to/test1234/node_modules/rollup/dist/shared/loadConfigFile.js:621:20)
    at Module.load (node:internal/modules/cjs/loader:998:32)
    at Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1022:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at loadConfigFromBundledFile (/path/to/test1234/node_modules/rollup/dist/shared/loadConfigFile.js:631:42)

$ npm run build                                                                                                                                                                                             

> test1234@0.0.0 prebuild
> npm run ci && npm run clean


> test1234@0.0.0 ci
> npm run lint


> test1234@0.0.0 lint
> eslint --ext .ts .

Error: Error while loading rule '@typescript-eslint/no-loss-of-precision': @typescript-eslint/no-loss-of-precision requires at least ESLint v7.1.0
Occurred while linting /path/to/test1234/src/index.d.ts
    at create (/path/to/test1234/node_modules/@typescript-eslint/eslint-plugin/dist/rules/no-loss-of-precision.js:46:19)
    at Object.create (/path/to/test1234/node_modules/@typescript-eslint/utils/dist/eslint-utils/RuleCreator.js:42:20)
    at createRuleListeners (/path/to/test1234/node_modules/eslint/lib/linter/linter.js:746:21)
    at /path/to/test1234/node_modules/eslint/lib/linter/linter.js:916:31
    at Array.forEach (<anonymous>)
    at runRules (/path/to/test1234/node_modules/eslint/lib/linter/linter.js:861:34)
    at Linter._verifyWithoutProcessors (/path/to/test1234/node_modules/eslint/lib/linter/linter.js:1157:31)
    at Linter._verifyWithConfigArray (/path/to/test1234/node_modules/eslint/lib/linter/linter.js:1255:21)
    at Linter.verify (/path/to/test1234/node_modules/eslint/lib/linter/linter.js:1210:25)
    at Linter.verifyAndFix (/path/to/test1234/node_modules/eslint/lib/linter/linter.js:1400:29)
```

</details>

**Comment by gera2ld** [comment]
Hi, it seems to be a bug of `npm`/`npx` and they have already fixed it.
Can you update your `npm` to the latest version and retry?

```bash
$ npm i npm -g
```

**Comment by KnifeFed** [comment]
Yup, works now, thanks!
